name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_HOST: https://matapi.messenger.fridaysforfuture.dev
      SSR: false
      TARGET: static
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate static files
        run: yarn run generate
        env:
          KC_REALM: https://dev-auth.messenger.fridaysforfuture.dev/auth/realms/dev
          OIDC_CLIENT: regio
          API_PATH: http://localhost:8000

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: regiobuddy.deee4future.me
